// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/invite": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a Firebase user and their profile. Returns a temporary password to share with the new user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Invite a new user",
                "parameters": [
                    {
                        "description": "User first name, last name and email",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.inviteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.inviteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/users/{uid}/role": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the user's role in the database. Takes effect immediately on the next request (no token refresh needed).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Grant or revoke admin role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Firebase UID of the target user",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.setRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Called after a successful Firebase login. Creates the user profile on first login, or returns the existing one.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sync user profile",
                "parameters": [
                    {
                        "description": "User first and last name (required on first login)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.syncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.User"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matches": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "List all matches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a match with set scores (best of 3, 21 points per set), recalculates ELO ratings, and records history.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Create a match",
                "parameters": [
                    {
                        "description": "Match details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matches/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Get a match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.Match"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/news": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Latest first. Anyone authenticated can read.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "List news",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max items to return (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.News"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. The created news has source = \"MANUAL\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Create a manual news item",
                "parameters": [
                    {
                        "description": "News payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.newsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db.News"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/news/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get a news item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.News"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Updates emoji, title and body. Source and references are immutable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Update a news item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "News payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.newsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.News"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Delete a news item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rankings": {
            "get": {
                "description": "Use /rankings/elo?tableau=... for new clients.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "ELO leaderboard (legacy — defaults to SINGLES)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.EloRanking"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rankings/elo": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "ELO leaderboard for a tableau",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SINGLES (default) | DOUBLES | MIXED",
                        "name": "tableau",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.EloRanking"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rankings/giant-killer": {
            "get": {
                "description": "Wins against an opponent whose ELO at match time exceeded the player's by at least UpsetThreshold.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "Giant-killer ranking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SINGLES (default) | DOUBLES | MIXED",
                        "name": "tableau",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM (default: current month)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.GiantKillerRanking"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rankings/league": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "League ranking (wins / losses / sets)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SINGLES (default) | DOUBLES | MIXED",
                        "name": "tableau",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM (default: current month)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.LeagueRanking"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rankings/matches-played": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "Matches-played ranking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SINGLES (default) | DOUBLES | MIXED",
                        "name": "tableau",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM (default: current month)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.MatchesPlayedRanking"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rankings/performance": {
            "get": {
                "description": "Sum of performance points awarded during the period for the tableau.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rankings"
                ],
                "summary": "Performance ranking (yellow jersey)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SINGLES (default) | DOUBLES | MIXED",
                        "name": "tableau",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM (default: current month)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.PerformanceRanking"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (Firebase UID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Users can only update their own profile. Admins can update any profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (Firebase UID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Users can only delete their own account. Admins can delete any account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (Firebase UID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/matches": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the user's SINGLES matches sorted DESC by played_at, reshaped from the user's perspective (sets as mine vs opp, signed ELO delta).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List a user's match history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (Firebase UID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.UserMatchHistoryEntry"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Singles-only for the MVP. Returns ELO, monthly perf score + rank, 7-day perf gain, monthly stats (matches/wins/losses/upsets/streak), held jerseys, yellow-jersey threshold, daily perf-history sparkline, and head-to-head (nemesis + favorite victim).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Aggregated profile payload for the mobile profile screen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (Firebase UID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.UserProfile"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.Match": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "match_type": {
                    "$ref": "#/definitions/db.MatchType"
                },
                "played_at": {
                    "$ref": "#/definitions/pgtype.Timestamptz"
                },
                "set1_team1": {
                    "type": "integer"
                },
                "set1_team2": {
                    "type": "integer"
                },
                "set2_team1": {
                    "type": "integer"
                },
                "set2_team2": {
                    "type": "integer"
                },
                "set3_team1": {
                    "$ref": "#/definitions/pgtype.Int4"
                },
                "set3_team2": {
                    "$ref": "#/definitions/pgtype.Int4"
                },
                "team1_player1_id": {
                    "type": "string"
                },
                "team1_player2_id": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "team2_player1_id": {
                    "type": "string"
                },
                "team2_player2_id": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "db.MatchType": {
            "type": "string",
            "enum": [
                "SINGLES",
                "DOUBLES",
                "MIXED"
            ],
            "x-enum-varnames": [
                "MatchTypeSINGLES",
                "MatchTypeDOUBLES",
                "MatchTypeMIXED"
            ]
        },
        "db.News": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "created_at": {
                    "$ref": "#/definitions/pgtype.Timestamptz"
                },
                "created_by": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "emoji": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "db.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/pgtype.Timestamptz"
                },
                "elo_doubles": {
                    "type": "integer"
                },
                "elo_mixed": {
                    "type": "integer"
                },
                "elo_singles": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "ffbad_rank": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/pgtype.Text"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "handlers.createMatchRequest": {
            "type": "object",
            "properties": {
                "match_type": {
                    "description": "SINGLES | DOUBLES | MIXED",
                    "type": "string"
                },
                "sets": {
                    "description": "2 or 3 sets",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.setScore"
                    }
                },
                "team1_player1_id": {
                    "description": "always required",
                    "type": "string"
                },
                "team1_player2_id": {
                    "description": "required for DOUBLES / MIXED",
                    "type": "string"
                },
                "team2_player1_id": {
                    "description": "always required",
                    "type": "string"
                },
                "team2_player2_id": {
                    "description": "required for DOUBLES / MIXED",
                    "type": "string"
                }
            }
        },
        "handlers.inviteRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "handlers.inviteResponse": {
            "type": "object",
            "properties": {
                "temp_password": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/db.User"
                }
            }
        },
        "handlers.newsRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "optional",
                    "type": "string"
                },
                "emoji": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handlers.setRoleRequest": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                }
            }
        },
        "handlers.setScore": {
            "type": "object",
            "properties": {
                "team1": {
                    "type": "integer"
                },
                "team2": {
                    "type": "integer"
                }
            }
        },
        "handlers.syncRequest": {
            "type": "object",
            "properties": {
                "ffbad_rank": {
                    "description": "optional, NC | P12 | ... | N1",
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "description": "optional, MALE | FEMALE",
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "handlers.updateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "ffbad_rank": {
                    "description": "\"\" | NC | P12 | ... | N1",
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "description": "\"\" | MALE | FEMALE",
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "pgtype.InfinityModifier": {
            "type": "integer",
            "format": "int32",
            "enum": [
                1,
                0,
                -1
            ],
            "x-enum-varnames": [
                "Infinity",
                "Finite",
                "NegativeInfinity"
            ]
        },
        "pgtype.Int4": {
            "type": "object",
            "properties": {
                "int32": {
                    "type": "integer",
                    "format": "int32"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "pgtype.Text": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "pgtype.Timestamptz": {
            "type": "object",
            "properties": {
                "infinityModifier": {
                    "$ref": "#/definitions/pgtype.InfinityModifier"
                },
                "time": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "services.EloRanking": {
            "type": "object",
            "properties": {
                "elo": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "tableau": {
                    "$ref": "#/definitions/db.MatchType"
                },
                "user": {
                    "$ref": "#/definitions/db.User"
                }
            }
        },
        "services.GiantKillerRanking": {
            "type": "object",
            "properties": {
                "rank": {
                    "type": "integer"
                },
                "upset_wins": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/db.User"
                }
            }
        },
        "services.LeagueRanking": {
            "type": "object",
            "properties": {
                "losses": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "sets_diff": {
                    "type": "integer"
                },
                "sets_lost": {
                    "type": "integer"
                },
                "sets_won": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/db.User"
                },
                "wins": {
                    "type": "integer"
                }
            }
        },
        "services.MatchSet": {
            "type": "object",
            "properties": {
                "mine": {
                    "type": "integer"
                },
                "opp": {
                    "type": "integer"
                }
            }
        },
        "services.MatchesPlayedRanking": {
            "type": "object",
            "properties": {
                "matches_played": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/db.User"
                }
            }
        },
        "services.PerformanceRanking": {
            "type": "object",
            "properties": {
                "points": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/db.User"
                }
            }
        },
        "services.ProfileHeadToHead": {
            "type": "object",
            "properties": {
                "favorite_victim": {
                    "$ref": "#/definitions/services.ProfileOpponent"
                },
                "nemesis": {
                    "$ref": "#/definitions/services.ProfileOpponent"
                }
            }
        },
        "services.ProfileHistoryPoint": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "services.ProfileOpponent": {
            "type": "object",
            "properties": {
                "losses": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/services.ProfileUser"
                },
                "wins": {
                    "type": "integer"
                }
            }
        },
        "services.ProfilePerformance": {
            "type": "object",
            "properties": {
                "gain_7d": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "services.ProfileStatsMonth": {
            "type": "object",
            "properties": {
                "losses": {
                    "type": "integer"
                },
                "matches": {
                    "type": "integer"
                },
                "streak": {
                    "type": "integer"
                },
                "upset_wins": {
                    "type": "integer"
                },
                "wins": {
                    "type": "integer"
                }
            }
        },
        "services.ProfileUser": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "joined_year": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "services.UserMatchHistoryEntry": {
            "type": "object",
            "properties": {
                "elo_change": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "opponent": {
                    "$ref": "#/definitions/services.ProfileUser"
                },
                "perf_points": {
                    "type": "integer"
                },
                "played_at": {
                    "type": "string"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.MatchSet"
                    }
                },
                "tableau": {
                    "$ref": "#/definitions/db.MatchType"
                },
                "validated": {
                    "type": "boolean"
                },
                "won_by_user": {
                    "type": "boolean"
                }
            }
        },
        "services.UserProfile": {
            "type": "object",
            "properties": {
                "elo": {
                    "type": "integer"
                },
                "head_to_head": {
                    "$ref": "#/definitions/services.ProfileHeadToHead"
                },
                "jerseys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "perf_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.ProfileHistoryPoint"
                    }
                },
                "performance": {
                    "$ref": "#/definitions/services.ProfilePerformance"
                },
                "stats_month": {
                    "$ref": "#/definitions/services.ProfileStatsMonth"
                },
                "tableau": {
                    "$ref": "#/definitions/db.MatchType"
                },
                "user": {
                    "$ref": "#/definitions/services.ProfileUser"
                },
                "yellow_jersey_threshold": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Firebase ID Token — format: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BAP Pulse API",
	Description:      "REST API for the BAP Pulse badminton club app — Bad A Paname.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
