// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzF_sisS1ilx0cMIrAoUi-GHQ_iCRdaII',
    appId: '1:239139234503:web:56c523f8178ad66a2fd4e2',
    messagingSenderId: '239139234503',
    projectId: 'bap-pulse',
    authDomain: 'bap-pulse.firebaseapp.com',
    storageBucket: 'bap-pulse.firebasestorage.app',
    measurementId: 'G-DQHCYFTN43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNayT5EU6FmhYP33tJwhvHqSJVWmGsbZw',
    appId: '1:239139234503:android:91bbff631f09c9002fd4e2',
    messagingSenderId: '239139234503',
    projectId: 'bap-pulse',
    storageBucket: 'bap-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQnWrpryOgKPStaZbUsXujeEa-3cvfiPo',
    appId: '1:239139234503:ios:8e7f9fe43710c9c82fd4e2',
    messagingSenderId: '239139234503',
    projectId: 'bap-pulse',
    storageBucket: 'bap-pulse.firebasestorage.app',
    iosClientId:
        '239139234503-vlnnipcniuq2vth0tag96jg8n8v9v5os.apps.googleusercontent.com',
    iosBundleId: 'fr.bap75.bappulse',
  );
}
