// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (
    from_user_id, to_user_id, match_type, proposed_at, court, note
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, from_user_id, to_user_id, match_type, proposed_at, court, note, status, created_at, responded_at
`

type CreateChallengeParams struct {
	FromUserID string             `json:"from_user_id"`
	ToUserID   string             `json:"to_user_id"`
	MatchType  MatchType          `json:"match_type"`
	ProposedAt pgtype.Timestamptz `json:"proposed_at"`
	Court      pgtype.Text        `json:"court"`
	Note       pgtype.Text        `json:"note"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.FromUserID,
		arg.ToUserID,
		arg.MatchType,
		arg.ProposedAt,
		arg.Court,
		arg.Note,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.MatchType,
		&i.ProposedAt,
		&i.Court,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, from_user_id, to_user_id, match_type, proposed_at, court, note, status, created_at, responded_at FROM challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.MatchType,
		&i.ProposedAt,
		&i.Court,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const listChallengesForUser = `-- name: ListChallengesForUser :many
SELECT id, from_user_id, to_user_id, match_type, proposed_at, court, note, status, created_at, responded_at FROM challenges
WHERE from_user_id = $1 OR to_user_id = $1
ORDER BY created_at DESC
`

// Both sides — what the user received and what they sent.
func (q *Queries) ListChallengesForUser(ctx context.Context, fromUserID string) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, listChallengesForUser, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Challenge{}
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.MatchType,
			&i.ProposedAt,
			&i.Court,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChallengeStatus = `-- name: UpdateChallengeStatus :one
UPDATE challenges
SET status       = $2,
    responded_at = NOW()
WHERE id = $1
RETURNING id, from_user_id, to_user_id, match_type, proposed_at, court, note, status, created_at, responded_at
`

type UpdateChallengeStatusParams struct {
	ID     pgtype.UUID     `json:"id"`
	Status ChallengeStatus `json:"status"`
}

func (q *Queries) UpdateChallengeStatus(ctx context.Context, arg UpdateChallengeStatusParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, updateChallengeStatus, arg.ID, arg.Status)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.MatchType,
		&i.ProposedAt,
		&i.Court,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}
