// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_roster.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRosterEntry = `-- name: DeleteRosterEntry :exec
DELETE FROM club_roster
WHERE license_number = $1
`

func (q *Queries) DeleteRosterEntry(ctx context.Context, licenseNumber string) error {
	_, err := q.db.Exec(ctx, deleteRosterEntry, licenseNumber)
	return err
}

const getLastRosterSync = `-- name: GetLastRosterSync :one
SELECT MAX(synced_at)::timestamptz AS last_synced_at FROM club_roster
`

func (q *Queries) GetLastRosterSync(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastRosterSync)
	var last_synced_at pgtype.Timestamptz
	err := row.Scan(&last_synced_at)
	return last_synced_at, err
}

const getRosterEntryByLicense = `-- name: GetRosterEntryByLicense :one
SELECT license_number, per_id, first_name, last_name, gender, rank_singles, rank_doubles, rank_mixed, cote_singles, cote_doubles, cote_mixed, is_data_public, matched_user_id, synced_at FROM club_roster
WHERE license_number = $1
`

func (q *Queries) GetRosterEntryByLicense(ctx context.Context, licenseNumber string) (ClubRoster, error) {
	row := q.db.QueryRow(ctx, getRosterEntryByLicense, licenseNumber)
	var i ClubRoster
	err := row.Scan(
		&i.LicenseNumber,
		&i.PerID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.RankSingles,
		&i.RankDoubles,
		&i.RankMixed,
		&i.CoteSingles,
		&i.CoteDoubles,
		&i.CoteMixed,
		&i.IsDataPublic,
		&i.MatchedUserID,
		&i.SyncedAt,
	)
	return i, err
}

const listRoster = `-- name: ListRoster :many
SELECT license_number, per_id, first_name, last_name, gender, rank_singles, rank_doubles, rank_mixed, cote_singles, cote_doubles, cote_mixed, is_data_public, matched_user_id, synced_at FROM club_roster
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListRoster(ctx context.Context) ([]ClubRoster, error) {
	rows, err := q.db.Query(ctx, listRoster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubRoster{}
	for rows.Next() {
		var i ClubRoster
		if err := rows.Scan(
			&i.LicenseNumber,
			&i.PerID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.RankSingles,
			&i.RankDoubles,
			&i.RankMixed,
			&i.CoteSingles,
			&i.CoteDoubles,
			&i.CoteMixed,
			&i.IsDataPublic,
			&i.MatchedUserID,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRosterMatchedUser = `-- name: SetRosterMatchedUser :exec
UPDATE club_roster
SET matched_user_id = $2
WHERE license_number = $1
`

type SetRosterMatchedUserParams struct {
	LicenseNumber string      `json:"license_number"`
	MatchedUserID pgtype.Text `json:"matched_user_id"`
}

func (q *Queries) SetRosterMatchedUser(ctx context.Context, arg SetRosterMatchedUserParams) error {
	_, err := q.db.Exec(ctx, setRosterMatchedUser, arg.LicenseNumber, arg.MatchedUserID)
	return err
}

const upsertRosterEntry = `-- name: UpsertRosterEntry :one
INSERT INTO club_roster (
    license_number, per_id, first_name, last_name, gender,
    rank_singles, rank_doubles, rank_mixed,
    cote_singles, cote_doubles, cote_mixed,
    is_data_public, synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW())
ON CONFLICT (license_number) DO UPDATE SET
    per_id         = EXCLUDED.per_id,
    first_name     = EXCLUDED.first_name,
    last_name      = EXCLUDED.last_name,
    gender         = EXCLUDED.gender,
    rank_singles   = EXCLUDED.rank_singles,
    rank_doubles   = EXCLUDED.rank_doubles,
    rank_mixed     = EXCLUDED.rank_mixed,
    cote_singles   = EXCLUDED.cote_singles,
    cote_doubles   = EXCLUDED.cote_doubles,
    cote_mixed     = EXCLUDED.cote_mixed,
    is_data_public = EXCLUDED.is_data_public,
    synced_at      = NOW()
RETURNING license_number, per_id, first_name, last_name, gender, rank_singles, rank_doubles, rank_mixed, cote_singles, cote_doubles, cote_mixed, is_data_public, matched_user_id, synced_at
`

type UpsertRosterEntryParams struct {
	LicenseNumber string      `json:"license_number"`
	PerID         pgtype.Text `json:"per_id"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Gender        pgtype.Text `json:"gender"`
	RankSingles   pgtype.Text `json:"rank_singles"`
	RankDoubles   pgtype.Text `json:"rank_doubles"`
	RankMixed     pgtype.Text `json:"rank_mixed"`
	CoteSingles   pgtype.Int4 `json:"cote_singles"`
	CoteDoubles   pgtype.Int4 `json:"cote_doubles"`
	CoteMixed     pgtype.Int4 `json:"cote_mixed"`
	IsDataPublic  bool        `json:"is_data_public"`
}

func (q *Queries) UpsertRosterEntry(ctx context.Context, arg UpsertRosterEntryParams) (ClubRoster, error) {
	row := q.db.QueryRow(ctx, upsertRosterEntry,
		arg.LicenseNumber,
		arg.PerID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.RankSingles,
		arg.RankDoubles,
		arg.RankMixed,
		arg.CoteSingles,
		arg.CoteDoubles,
		arg.CoteMixed,
		arg.IsDataPublic,
	)
	var i ClubRoster
	err := row.Scan(
		&i.LicenseNumber,
		&i.PerID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.RankSingles,
		&i.RankDoubles,
		&i.RankMixed,
		&i.CoteSingles,
		&i.CoteDoubles,
		&i.CoteMixed,
		&i.IsDataPublic,
		&i.MatchedUserID,
		&i.SyncedAt,
	)
	return i, err
}
