// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elo_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEloHistory = `-- name: CreateEloHistory :one
INSERT INTO elo_history (player_id, elo_before, elo_after, match_id)
VALUES ($1, $2, $3, $4)
RETURNING id, player_id, elo_before, elo_after, match_id, created_at
`

type CreateEloHistoryParams struct {
	PlayerID  string      `json:"player_id"`
	EloBefore int32       `json:"elo_before"`
	EloAfter  int32       `json:"elo_after"`
	MatchID   pgtype.UUID `json:"match_id"`
}

func (q *Queries) CreateEloHistory(ctx context.Context, arg CreateEloHistoryParams) (EloHistory, error) {
	row := q.db.QueryRow(ctx, createEloHistory,
		arg.PlayerID,
		arg.EloBefore,
		arg.EloAfter,
		arg.MatchID,
	)
	var i EloHistory
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.EloBefore,
		&i.EloAfter,
		&i.MatchID,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchEloHistory = `-- name: GetMatchEloHistory :many
SELECT id, player_id, elo_before, elo_after, match_id, created_at FROM elo_history
WHERE match_id = $1
`

func (q *Queries) GetMatchEloHistory(ctx context.Context, matchID pgtype.UUID) ([]EloHistory, error) {
	rows, err := q.db.Query(ctx, getMatchEloHistory, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EloHistory{}
	for rows.Next() {
		var i EloHistory
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.EloBefore,
			&i.EloAfter,
			&i.MatchID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEloHistory = `-- name: GetUserEloHistory :many
SELECT id, player_id, elo_before, elo_after, match_id, created_at FROM elo_history
WHERE player_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserEloHistory(ctx context.Context, playerID string) ([]EloHistory, error) {
	rows, err := q.db.Query(ctx, getUserEloHistory, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EloHistory{}
	for rows.Next() {
		var i EloHistory
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.EloBefore,
			&i.EloAfter,
			&i.MatchID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
