// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fcm_tokens.sql

package db

import (
	"context"
)

const deleteFcmToken = `-- name: DeleteFcmToken :exec
DELETE FROM fcm_tokens
WHERE token = $1 AND user_id = $2
`

type DeleteFcmTokenParams struct {
	Token  string `json:"token"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteFcmToken(ctx context.Context, arg DeleteFcmTokenParams) error {
	_, err := q.db.Exec(ctx, deleteFcmToken, arg.Token, arg.UserID)
	return err
}

const deleteFcmTokensByValue = `-- name: DeleteFcmTokensByValue :exec
DELETE FROM fcm_tokens
WHERE token = ANY($1::text[])
`

// Used to purge tokens reported as unregistered/invalid by FCM.
func (q *Queries) DeleteFcmTokensByValue(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteFcmTokensByValue, dollar_1)
	return err
}

const listFcmTokensForUser = `-- name: ListFcmTokensForUser :many
SELECT token, user_id, platform, created_at, last_seen_at FROM fcm_tokens
WHERE user_id = $1
`

func (q *Queries) ListFcmTokensForUser(ctx context.Context, userID string) ([]FcmToken, error) {
	rows, err := q.db.Query(ctx, listFcmTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FcmToken{}
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(
			&i.Token,
			&i.UserID,
			&i.Platform,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFcmToken = `-- name: UpsertFcmToken :one
INSERT INTO fcm_tokens (token, user_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET user_id      = EXCLUDED.user_id,
    platform     = EXCLUDED.platform,
    last_seen_at = NOW()
RETURNING token, user_id, platform, created_at, last_seen_at
`

type UpsertFcmTokenParams struct {
	Token    string `json:"token"`
	UserID   string `json:"user_id"`
	Platform string `json:"platform"`
}

// Stores or refreshes a device token. Same token across users is rebound
// to the new user (a device can switch accounts).
func (q *Queries) UpsertFcmToken(ctx context.Context, arg UpsertFcmTokenParams) (FcmToken, error) {
	row := q.db.QueryRow(ctx, upsertFcmToken, arg.Token, arg.UserID, arg.Platform)
	var i FcmToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Platform,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
