// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    match_type,
    team1_player1_id, team1_player2_id,
    team2_player1_id, team2_player2_id,
    set1_team1, set1_team2,
    set2_team1, set2_team2,
    set3_team1, set3_team2,
    played_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, played_at, validated, set1_team1, set1_team2, set2_team1, set2_team2, set3_team1, set3_team2
`

type CreateMatchParams struct {
	MatchType      MatchType          `json:"match_type"`
	Team1Player1ID string             `json:"team1_player1_id"`
	Team1Player2ID pgtype.Text        `json:"team1_player2_id"`
	Team2Player1ID string             `json:"team2_player1_id"`
	Team2Player2ID pgtype.Text        `json:"team2_player2_id"`
	Set1Team1      int32              `json:"set1_team1"`
	Set1Team2      int32              `json:"set1_team2"`
	Set2Team1      int32              `json:"set2_team1"`
	Set2Team2      int32              `json:"set2_team2"`
	Set3Team1      pgtype.Int4        `json:"set3_team1"`
	Set3Team2      pgtype.Int4        `json:"set3_team2"`
	PlayedAt       pgtype.Timestamptz `json:"played_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.MatchType,
		arg.Team1Player1ID,
		arg.Team1Player2ID,
		arg.Team2Player1ID,
		arg.Team2Player2ID,
		arg.Set1Team1,
		arg.Set1Team2,
		arg.Set2Team1,
		arg.Set2Team2,
		arg.Set3Team1,
		arg.Set3Team2,
		arg.PlayedAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Team1Player1ID,
		&i.Team1Player2ID,
		&i.Team2Player1ID,
		&i.Team2Player2ID,
		&i.PlayedAt,
		&i.Validated,
		&i.Set1Team1,
		&i.Set1Team2,
		&i.Set2Team1,
		&i.Set2Team2,
		&i.Set3Team1,
		&i.Set3Team2,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, played_at, validated, set1_team1, set1_team2, set2_team1, set2_team2, set3_team1, set3_team2 FROM matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Team1Player1ID,
		&i.Team1Player2ID,
		&i.Team2Player1ID,
		&i.Team2Player2ID,
		&i.PlayedAt,
		&i.Validated,
		&i.Set1Team1,
		&i.Set1Team2,
		&i.Set2Team1,
		&i.Set2Team2,
		&i.Set3Team1,
		&i.Set3Team2,
	)
	return i, err
}

const getMatchesInPeriod = `-- name: GetMatchesInPeriod :many
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, played_at, validated, set1_team1, set1_team2, set2_team1, set2_team2, set3_team1, set3_team2 FROM matches
WHERE match_type = $1
  AND played_at >= $2
  AND played_at <  $3
ORDER BY played_at DESC
`

type GetMatchesInPeriodParams struct {
	MatchType  MatchType          `json:"match_type"`
	PlayedAt   pgtype.Timestamptz `json:"played_at"`
	PlayedAt_2 pgtype.Timestamptz `json:"played_at_2"`
}

func (q *Queries) GetMatchesInPeriod(ctx context.Context, arg GetMatchesInPeriodParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, getMatchesInPeriod, arg.MatchType, arg.PlayedAt, arg.PlayedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Team1Player1ID,
			&i.Team1Player2ID,
			&i.Team2Player1ID,
			&i.Team2Player2ID,
			&i.PlayedAt,
			&i.Validated,
			&i.Set1Team1,
			&i.Set1Team2,
			&i.Set2Team1,
			&i.Set2Team2,
			&i.Set3Team1,
			&i.Set3Team2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerMatches = `-- name: GetPlayerMatches :many
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, played_at, validated, set1_team1, set1_team2, set2_team1, set2_team2, set3_team1, set3_team2 FROM matches
WHERE team1_player1_id = $1 OR team1_player2_id = $1
   OR team2_player1_id = $1 OR team2_player2_id = $1
ORDER BY played_at DESC
`

func (q *Queries) GetPlayerMatches(ctx context.Context, team1Player1ID string) ([]Match, error) {
	rows, err := q.db.Query(ctx, getPlayerMatches, team1Player1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Team1Player1ID,
			&i.Team1Player2ID,
			&i.Team2Player1ID,
			&i.Team2Player2ID,
			&i.PlayedAt,
			&i.Validated,
			&i.Set1Team1,
			&i.Set1Team2,
			&i.Set2Team1,
			&i.Set2Team2,
			&i.Set3Team1,
			&i.Set3Team2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, played_at, validated, set1_team1, set1_team2, set2_team1, set2_team2, set3_team1, set3_team2 FROM matches
ORDER BY played_at DESC
`

func (q *Queries) ListMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Team1Player1ID,
			&i.Team1Player2ID,
			&i.Team2Player1ID,
			&i.Team2Player2ID,
			&i.PlayedAt,
			&i.Validated,
			&i.Set1Team1,
			&i.Set1Team2,
			&i.Set2Team1,
			&i.Set2Team2,
			&i.Set3Team1,
			&i.Set3Team2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateMatch = `-- name: ValidateMatch :one
UPDATE matches
SET validated = true
WHERE id = $1
RETURNING id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, played_at, validated, set1_team1, set1_team2, set2_team1, set2_team2, set3_team1, set3_team2
`

func (q *Queries) ValidateMatch(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, validateMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Team1Player1ID,
		&i.Team1Player2ID,
		&i.Team2Player1ID,
		&i.Team2Player2ID,
		&i.PlayedAt,
		&i.Validated,
		&i.Set1Team1,
		&i.Set1Team2,
		&i.Set2Team1,
		&i.Set2Team2,
		&i.Set3Team1,
		&i.Set3Team2,
	)
	return i, err
}
