// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    match_type,
    team1_player1_id, team1_player2_id,
    team2_player1_id, team2_player2_id,
    score_team1, score_team2,
    played_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, score_team1, score_team2, played_at, validated
`

type CreateMatchParams struct {
	MatchType      MatchType          `json:"match_type"`
	Team1Player1ID string             `json:"team1_player1_id"`
	Team1Player2ID pgtype.Text        `json:"team1_player2_id"`
	Team2Player1ID string             `json:"team2_player1_id"`
	Team2Player2ID pgtype.Text        `json:"team2_player2_id"`
	ScoreTeam1     int32              `json:"score_team1"`
	ScoreTeam2     int32              `json:"score_team2"`
	PlayedAt       pgtype.Timestamptz `json:"played_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.MatchType,
		arg.Team1Player1ID,
		arg.Team1Player2ID,
		arg.Team2Player1ID,
		arg.Team2Player2ID,
		arg.ScoreTeam1,
		arg.ScoreTeam2,
		arg.PlayedAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Team1Player1ID,
		&i.Team1Player2ID,
		&i.Team2Player1ID,
		&i.Team2Player2ID,
		&i.ScoreTeam1,
		&i.ScoreTeam2,
		&i.PlayedAt,
		&i.Validated,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, score_team1, score_team2, played_at, validated FROM matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Team1Player1ID,
		&i.Team1Player2ID,
		&i.Team2Player1ID,
		&i.Team2Player2ID,
		&i.ScoreTeam1,
		&i.ScoreTeam2,
		&i.PlayedAt,
		&i.Validated,
	)
	return i, err
}

const getPlayerMatches = `-- name: GetPlayerMatches :many
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, score_team1, score_team2, played_at, validated FROM matches
WHERE team1_player1_id = $1 OR team1_player2_id = $1
   OR team2_player1_id = $1 OR team2_player2_id = $1
ORDER BY played_at DESC
`

func (q *Queries) GetPlayerMatches(ctx context.Context, team1Player1ID string) ([]Match, error) {
	rows, err := q.db.Query(ctx, getPlayerMatches, team1Player1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Team1Player1ID,
			&i.Team1Player2ID,
			&i.Team2Player1ID,
			&i.Team2Player2ID,
			&i.ScoreTeam1,
			&i.ScoreTeam2,
			&i.PlayedAt,
			&i.Validated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, score_team1, score_team2, played_at, validated FROM matches
ORDER BY played_at DESC
`

func (q *Queries) ListMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Team1Player1ID,
			&i.Team1Player2ID,
			&i.Team2Player1ID,
			&i.Team2Player2ID,
			&i.ScoreTeam1,
			&i.ScoreTeam2,
			&i.PlayedAt,
			&i.Validated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateMatch = `-- name: ValidateMatch :one
UPDATE matches
SET validated = true
WHERE id = $1
RETURNING id, match_type, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, score_team1, score_team2, played_at, validated
`

func (q *Queries) ValidateMatch(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, validateMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Team1Player1ID,
		&i.Team1Player2ID,
		&i.Team2Player1ID,
		&i.Team2Player2ID,
		&i.ScoreTeam1,
		&i.ScoreTeam2,
		&i.PlayedAt,
		&i.Validated,
	)
	return i, err
}
