// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MatchType string

const (
	MatchTypeSINGLES MatchType = "SINGLES"
	MatchTypeDOUBLES MatchType = "DOUBLES"
	MatchTypeMIXED   MatchType = "MIXED"
)

func (e *MatchType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchType(s)
	case string:
		*e = MatchType(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchType: %T", src)
	}
	return nil
}

type NullMatchType struct {
	MatchType MatchType `json:"match_type"`
	Valid     bool      `json:"valid"` // Valid is true if MatchType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchType) Scan(value interface{}) error {
	if value == nil {
		ns.MatchType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchType), nil
}

type EloHistory struct {
	ID        pgtype.UUID        `json:"id"`
	PlayerID  string             `json:"player_id"`
	EloBefore int32              `json:"elo_before"`
	EloAfter  int32              `json:"elo_after"`
	MatchID   pgtype.UUID        `json:"match_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID             pgtype.UUID        `json:"id"`
	MatchType      MatchType          `json:"match_type"`
	Team1Player1ID string             `json:"team1_player1_id"`
	Team1Player2ID pgtype.Text        `json:"team1_player2_id"`
	Team2Player1ID string             `json:"team2_player1_id"`
	Team2Player2ID pgtype.Text        `json:"team2_player2_id"`
	ScoreTeam1     int32              `json:"score_team1"`
	ScoreTeam2     int32              `json:"score_team2"`
	PlayedAt       pgtype.Timestamptz `json:"played_at"`
	Validated      bool               `json:"validated"`
}

type Player struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Elo       int32              `json:"elo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
