// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNews = `-- name: CreateNews :one
INSERT INTO news (
    emoji, title, body, source, match_id, created_by
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, emoji, title, body, source, match_id, created_by, created_at
`

type CreateNewsParams struct {
	Emoji     string      `json:"emoji"`
	Title     string      `json:"title"`
	Body      pgtype.Text `json:"body"`
	Source    string      `json:"source"`
	MatchID   pgtype.UUID `json:"match_id"`
	CreatedBy pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, createNews,
		arg.Emoji,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.MatchID,
		arg.CreatedBy,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.MatchID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNews = `-- name: DeleteNews :exec
DELETE FROM news
WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNews, id)
	return err
}

const getNewsByID = `-- name: GetNewsByID :one
SELECT id, emoji, title, body, source, match_id, created_by, created_at FROM news
WHERE id = $1
`

func (q *Queries) GetNewsByID(ctx context.Context, id pgtype.UUID) (News, error) {
	row := q.db.QueryRow(ctx, getNewsByID, id)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.MatchID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestNews = `-- name: ListLatestNews :many
SELECT id, emoji, title, body, source, match_id, created_by, created_at FROM news
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListLatestNews(ctx context.Context, limit int32) ([]News, error) {
	rows, err := q.db.Query(ctx, listLatestNews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []News{}
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.MatchID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNews = `-- name: ListNews :many
SELECT id, emoji, title, body, source, match_id, created_by, created_at FROM news
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNews(ctx context.Context, arg ListNewsParams) ([]News, error) {
	rows, err := q.db.Query(ctx, listNews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []News{}
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.MatchID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNews = `-- name: UpdateNews :one
UPDATE news
SET emoji = $2,
    title = $3,
    body  = $4
WHERE id = $1
RETURNING id, emoji, title, body, source, match_id, created_by, created_at
`

type UpdateNewsParams struct {
	ID    pgtype.UUID `json:"id"`
	Emoji string      `json:"emoji"`
	Title string      `json:"title"`
	Body  pgtype.Text `json:"body"`
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, updateNews,
		arg.ID,
		arg.Emoji,
		arg.Title,
		arg.Body,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.MatchID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
