// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, name, email)
VALUES ($1, $2, $3)
RETURNING id, name, email, elo, created_at
`

type CreatePlayerParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.ID, arg.Name, arg.Email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, name, email, elo, created_at FROM players
WHERE email = $1
`

func (q *Queries) GetPlayerByEmail(ctx context.Context, email string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, name, email, elo, created_at FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, email, elo, created_at FROM players
ORDER BY elo DESC, created_at ASC
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Elo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET name = $2, email = $3
WHERE id = $1
RETURNING id, name, email, elo, created_at
`

type UpdatePlayerParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer, arg.ID, arg.Name, arg.Email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlayerElo = `-- name: UpdatePlayerElo :one
UPDATE players
SET elo = $2
WHERE id = $1
RETURNING id, name, email, elo, created_at
`

type UpdatePlayerEloParams struct {
	ID  string `json:"id"`
	Elo int32  `json:"elo"`
}

func (q *Queries) UpdatePlayerElo(ctx context.Context, arg UpdatePlayerEloParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerElo, arg.ID, arg.Elo)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
	)
	return i, err
}
