// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEloHistory(ctx context.Context, arg CreateEloHistoryParams) (EloHistory, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id string) error
	GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error)
	GetMatchEloHistory(ctx context.Context, matchID pgtype.UUID) ([]EloHistory, error)
	GetPlayerMatches(ctx context.Context, team1Player1ID string) ([]Match, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserEloHistory(ctx context.Context, playerID string) ([]EloHistory, error)
	ListMatches(ctx context.Context) ([]Match, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserElo(ctx context.Context, arg UpdateUserEloParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	ValidateMatch(ctx context.Context, id pgtype.UUID) (Match, error)
}

var _ Querier = (*Queries)(nil)
