// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, first_name, last_name, email)
VALUES ($1, $2, $3, $4)
RETURNING id, email, elo, created_at, role, first_name, last_name
`

type CreateUserParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, elo, created_at, role, first_name, last_name FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, elo, created_at, role, first_name, last_name FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, elo, created_at, role, first_name, last_name FROM users
ORDER BY elo DESC, created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Elo,
			&i.CreatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2, last_name = $3, email = $4
WHERE id = $1
RETURNING id, email, elo, created_at, role, first_name, last_name
`

type UpdateUserParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateUserElo = `-- name: UpdateUserElo :one
UPDATE users
SET elo = $2
WHERE id = $1
RETURNING id, email, elo, created_at, role, first_name, last_name
`

type UpdateUserEloParams struct {
	ID  string `json:"id"`
	Elo int32  `json:"elo"`
}

func (q *Queries) UpdateUserElo(ctx context.Context, arg UpdateUserEloParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserElo, arg.ID, arg.Elo)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, email, elo, created_at, role, first_name, last_name
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Elo,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
