// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, first_name, last_name, email,
    gender, ffbad_rank,
    elo_singles, elo_doubles, elo_mixed
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type CreateUserParams struct {
	ID         string      `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      string      `json:"email"`
	Gender     pgtype.Text `json:"gender"`
	FfbadRank  pgtype.Text `json:"ffbad_rank"`
	EloSingles int32       `json:"elo_singles"`
	EloDoubles int32       `json:"elo_doubles"`
	EloMixed   int32       `json:"elo_mixed"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Gender,
		arg.FfbadRank,
		arg.EloSingles,
		arg.EloDoubles,
		arg.EloMixed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname FROM users
ORDER BY elo_singles DESC, created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.FfbadRank,
			&i.EloSingles,
			&i.EloDoubles,
			&i.EloMixed,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2,
    last_name  = $3,
    email      = $4,
    gender     = $5,
    ffbad_rank = $6,
    nickname   = $7
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type UpdateUserParams struct {
	ID        string      `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	Gender    pgtype.Text `json:"gender"`
	FfbadRank pgtype.Text `json:"ffbad_rank"`
	Nickname  pgtype.Text `json:"nickname"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Gender,
		arg.FfbadRank,
		arg.Nickname,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const updateUserEloDoubles = `-- name: UpdateUserEloDoubles :one
UPDATE users
SET elo_doubles = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type UpdateUserEloDoublesParams struct {
	ID         string `json:"id"`
	EloDoubles int32  `json:"elo_doubles"`
}

func (q *Queries) UpdateUserEloDoubles(ctx context.Context, arg UpdateUserEloDoublesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEloDoubles, arg.ID, arg.EloDoubles)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const updateUserEloMixed = `-- name: UpdateUserEloMixed :one
UPDATE users
SET elo_mixed = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type UpdateUserEloMixedParams struct {
	ID       string `json:"id"`
	EloMixed int32  `json:"elo_mixed"`
}

func (q *Queries) UpdateUserEloMixed(ctx context.Context, arg UpdateUserEloMixedParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEloMixed, arg.ID, arg.EloMixed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const updateUserEloSingles = `-- name: UpdateUserEloSingles :one
UPDATE users
SET elo_singles = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type UpdateUserEloSinglesParams struct {
	ID         string `json:"id"`
	EloSingles int32  `json:"elo_singles"`
}

func (q *Queries) UpdateUserEloSingles(ctx context.Context, arg UpdateUserEloSinglesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEloSingles, arg.ID, arg.EloSingles)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const updateUserInitialElo = `-- name: UpdateUserInitialElo :one
UPDATE users
SET elo_singles = $2,
    elo_doubles = $3,
    elo_mixed   = $4
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type UpdateUserInitialEloParams struct {
	ID         string `json:"id"`
	EloSingles int32  `json:"elo_singles"`
	EloDoubles int32  `json:"elo_doubles"`
	EloMixed   int32  `json:"elo_mixed"`
}

// Used when a user updates their FFBAD/gender BEFORE having played any match.
func (q *Queries) UpdateUserInitialElo(ctx context.Context, arg UpdateUserInitialEloParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInitialElo,
		arg.ID,
		arg.EloSingles,
		arg.EloDoubles,
		arg.EloMixed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
	)
	return i, err
}
