// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveUserFromRoster = `-- name: ApproveUserFromRoster :one
UPDATE users
SET status      = 'approved',
    gender      = COALESCE($2, gender),
    ffbad_rank  = COALESCE($3, ffbad_rank),
    elo_singles = $4,
    elo_doubles = $5,
    elo_mixed   = $6
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type ApproveUserFromRosterParams struct {
	ID         string      `json:"id"`
	Gender     pgtype.Text `json:"gender"`
	FfbadRank  pgtype.Text `json:"ffbad_rank"`
	EloSingles int32       `json:"elo_singles"`
	EloDoubles int32       `json:"elo_doubles"`
	EloMixed   int32       `json:"elo_mixed"`
}

// Used when a roster sync matches a previously-registered pending user: flips
// them to approved and seeds gender/rank/ELO from the FFBAD roster entry.
func (q *Queries) ApproveUserFromRoster(ctx context.Context, arg ApproveUserFromRosterParams) (User, error) {
	row := q.db.QueryRow(ctx, approveUserFromRoster,
		arg.ID,
		arg.Gender,
		arg.FfbadRank,
		arg.EloSingles,
		arg.EloDoubles,
		arg.EloMixed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, first_name, last_name, email,
    gender, ffbad_rank,
    elo_singles, elo_doubles, elo_mixed,
    status, license_number
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type CreateUserParams struct {
	ID            string      `json:"id"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Email         string      `json:"email"`
	Gender        pgtype.Text `json:"gender"`
	FfbadRank     pgtype.Text `json:"ffbad_rank"`
	EloSingles    int32       `json:"elo_singles"`
	EloDoubles    int32       `json:"elo_doubles"`
	EloMixed      int32       `json:"elo_mixed"`
	Status        UserStatus  `json:"status"`
	LicenseNumber pgtype.Text `json:"license_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Gender,
		arg.FfbadRank,
		arg.EloSingles,
		arg.EloDoubles,
		arg.EloMixed,
		arg.Status,
		arg.LicenseNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const getUserByLicenseNumber = `-- name: GetUserByLicenseNumber :one
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number FROM users
WHERE license_number = $1
`

func (q *Queries) GetUserByLicenseNumber(ctx context.Context, licenseNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLicenseNumber, licenseNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number FROM users
ORDER BY elo_singles DESC, created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.FfbadRank,
			&i.EloSingles,
			&i.EloDoubles,
			&i.EloMixed,
			&i.Nickname,
			&i.Status,
			&i.LicenseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStatus = `-- name: ListUsersByStatus :many
SELECT id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number FROM users
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) ListUsersByStatus(ctx context.Context, status UserStatus) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.FfbadRank,
			&i.EloSingles,
			&i.EloDoubles,
			&i.EloMixed,
			&i.Nickname,
			&i.Status,
			&i.LicenseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserGenderAndRank = `-- name: SetUserGenderAndRank :one
UPDATE users
SET gender     = COALESCE($2, gender),
    ffbad_rank = COALESCE($3, ffbad_rank)
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type SetUserGenderAndRankParams struct {
	ID        string      `json:"id"`
	Gender    pgtype.Text `json:"gender"`
	FfbadRank pgtype.Text `json:"ffbad_rank"`
}

// Used when an admin corrects a user's gender/FFBAD rank (e.g. at approval).
// NULL params leave the existing value untouched.
func (q *Queries) SetUserGenderAndRank(ctx context.Context, arg SetUserGenderAndRankParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserGenderAndRank, arg.ID, arg.Gender, arg.FfbadRank)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2,
    last_name  = $3,
    email      = $4,
    gender     = $5,
    ffbad_rank = $6,
    nickname   = $7
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserParams struct {
	ID        string      `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	Gender    pgtype.Text `json:"gender"`
	FfbadRank pgtype.Text `json:"ffbad_rank"`
	Nickname  pgtype.Text `json:"nickname"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Gender,
		arg.FfbadRank,
		arg.Nickname,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUserEloDoubles = `-- name: UpdateUserEloDoubles :one
UPDATE users
SET elo_doubles = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserEloDoublesParams struct {
	ID         string `json:"id"`
	EloDoubles int32  `json:"elo_doubles"`
}

func (q *Queries) UpdateUserEloDoubles(ctx context.Context, arg UpdateUserEloDoublesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEloDoubles, arg.ID, arg.EloDoubles)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUserEloMixed = `-- name: UpdateUserEloMixed :one
UPDATE users
SET elo_mixed = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserEloMixedParams struct {
	ID       string `json:"id"`
	EloMixed int32  `json:"elo_mixed"`
}

func (q *Queries) UpdateUserEloMixed(ctx context.Context, arg UpdateUserEloMixedParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEloMixed, arg.ID, arg.EloMixed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUserEloSingles = `-- name: UpdateUserEloSingles :one
UPDATE users
SET elo_singles = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserEloSinglesParams struct {
	ID         string `json:"id"`
	EloSingles int32  `json:"elo_singles"`
}

func (q *Queries) UpdateUserEloSingles(ctx context.Context, arg UpdateUserEloSinglesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEloSingles, arg.ID, arg.EloSingles)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUserInitialElo = `-- name: UpdateUserInitialElo :one
UPDATE users
SET elo_singles = $2,
    elo_doubles = $3,
    elo_mixed   = $4
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserInitialEloParams struct {
	ID         string `json:"id"`
	EloSingles int32  `json:"elo_singles"`
	EloDoubles int32  `json:"elo_doubles"`
	EloMixed   int32  `json:"elo_mixed"`
}

// Used when a user updates their FFBAD/gender BEFORE having played any match.
func (q *Queries) UpdateUserInitialElo(ctx context.Context, arg UpdateUserInitialEloParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInitialElo,
		arg.ID,
		arg.EloSingles,
		arg.EloDoubles,
		arg.EloMixed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2
WHERE id = $1
RETURNING id, email, created_at, role, first_name, last_name, gender, ffbad_rank, elo_singles, elo_doubles, elo_mixed, nickname, status, license_number
`

type UpdateUserStatusParams struct {
	ID     string     `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.FfbadRank,
		&i.EloSingles,
		&i.EloDoubles,
		&i.EloMixed,
		&i.Nickname,
		&i.Status,
		&i.LicenseNumber,
	)
	return i, err
}
